---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: tshnode
  name: tshnode
  namespace: teleport
spec:
  selector:
    matchLabels:
      k8s-app: tshnode
  template:
    metadata:
      labels:
        k8s-app: tshnode
    spec:
      containers:
      - image: amazonlinux
        imagePullPolicy: Always
        name: ssm
        command: ["/bin/bash"]
        args: 
          - -c
          - |
            yum-config-manager --add-repo https://rpm.releases.teleport.dev/teleport.repo ;
            yum install teleport ;
            teleport start --roles=node --token=XXX --auth-server=teleport-cluster.teleport:443
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 2
