---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: secrets-store-csi-driver
  namespace: flux-system
spec:
  interval: 1m
  url: https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-secrets-store
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: "0.2.0"
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
        namespace: flux-system
      interval: 1m
  values:
    grpcSupportedProviders: aws
