---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: gitlab
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.gitlab.io/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 5m
  chart:
    spec:
      chart: gitlab
      version: "4.11.3"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 1m
  values:
    global:
      ingress:
        enabled: true
      psql:
        password:
          secret: rds-pw-gitlab
          key: password
      redis:
        scheme: rediss
        password:
          secret: rds-pw-gitlab
          key: redispw
    postgresql:
      install: false
    redis:
      install: false
  valuesFrom:
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: cluster_name
      targetPath: clusterName
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: domain
      targetPath: global.hosts.domain
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: certmanager-issuer-email
      targetPath: certmanager-issuer.email
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: pghost
      targetPath: global.psql.host
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: pgport
      targetPath: global.psql.port
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: redisport
      targetPath: global.redis.port
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: redishost
      targetPath: global.redis.host
