---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: gitlab
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.gitlab.io/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 5m
  chart:
    spec:
      chart: gitlab/gitlab
      version: "4.10.2"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: gitlab
      interval: 1m
  values:
    global:
      ingress:
        enabled: true
  valuesFrom:
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: cluster_name
      targetPath: clusterName
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: domain
      targetPath: global.hosts.domain
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: certmanager-issuer-email
      targetPath: certmanager-issuer.email
