---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: gitlab
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.gitlab.io/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 5m
  chart:
    spec:
      chart: gitlab
      version: "4.11.4"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 1m
  values:
    gitlab:
      task-runner:
        enabled: true
        serviceAccount:
          create: true
          enabled: true
    gitlab-runner:
      runners:
        serviceAccountName: gitlab-gitlab-runner
      rbac:
        create: true
        resources: ["pods", "pods/exec", "secrets"]
        verbs: ["get", "list", "watch", "create", "patch", "delete"]
    nginx-ingress:
      controller:
        scope:
          enabled: true
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - gitlab-nginx
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                    - gitlab-nginx
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                    - controller
                topologyKey: kubernetes.io/hostname
        service:
          externalTrafficPolicy: Cluster
          enableHttp: false
          targetPorts:
            https: http
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Name=gitlab-nginx,class=nginx,role=test,vpc=test
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
            service.beta.kubernetes.io/aws-load-balancer-type: external
            service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: "preserve_client_ip.enabled=false"
        config:
          use-forwarded-headers: "true"
          client-header-timeout: "420"
          proxy-stream-timeout: "200s"
          client-body-timeout: "420"
        headers:
          X-Forwarded-Ssl: "on"
        stats:
          enabled: true
        metrics:
          enabled: true
      podSecurityPolicy:
        enabled: true
      serviceAccount:
        create: true
    certmanager:
      install: false
    global:
      ingress:
        enabled: false
        configureCertmanager: false
        tls:
          enabled: false
      psql:
        password:
          secret: rds-pw-gitlab
          key: password
      redis:
        scheme: rediss
        password:
          secret: rds-pw-gitlab
          key: redispw
      email:
        display_name: "Login.gov GitLab"
      smtp:
        enabled: true
        starttls_auto: true
        port: 587
        authentication: login
        password:
          secret: ses-smtp
          key: password
      appConfig:
        omniauth:
          enabled: true
          allowSingleSignOn: ['github']
          blockAutoCreatedUsers: false
          providers:
            - secret: gitlab-github-auth
    postgresql:
      install: false
    redis:
      install: false
  valuesFrom:
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: cluster_name
      targetPath: clusterName
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: domain
      targetPath: global.hosts.domain
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: cluster_name
      targetPath: global.hosts.hostSuffix
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: gitlab_name
      targetPath: global.hosts.gitlab.name
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: fullhostname
      targetPath: global.hosts.gitlab.hostnameOverride
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: ci_server_url
      targetPath: gitlab-runner.gitlabUrl
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: ci_server_url
      targetPath: gitlab-runner.runners.cloneUrl
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: certmanager-issuer-email
      targetPath: certmanager-issuer.email
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: pghost
      targetPath: global.psql.host
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: pgport
      targetPath: global.psql.port
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: redisport
      targetPath: global.redis.port
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: redishost
      targetPath: global.redis.host
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: ingress-security-groups
      targetPath: nginx-ingress.controller.service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-security-groups
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: cert-arn
      targetPath: nginx-ingress.controller.service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-ssl-cert
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: email-from
      targetPath: global.email.from
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: smtp-endpoint
      targetPath: global.smtp.address
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: email-domain
      targetPath: global.smtp.domain
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: smtp-username
      targetPath: global.smtp.user_name
    - kind: ConfigMap
      name: terraform-gitlab-info
      valuesKey: runner-iam-role
      targetPath: gitlab-runner.rbac.serviceAccountAnnotations.eks\.amazonaws\.com/role-arn
