---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
spec:
  interval: 1m
  url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-ebs-csi-driver
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: aws-ebs-csi-driver
      version: "2.6.2"
      sourceRef:
        kind: HelmRepository
        name: aws-ebs-csi-driver
        namespace: flux-system
      interval: 1m
  values:
    controller:
      serviceAccount:
        create: false
        name: ebs-csi-controller-sa
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
