apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: ssm
  name: ssm
  namespace: default
spec:
  selector:
    matchLabels:
      k8s-app: ssm
  template:
    metadata:
      labels:
        k8s-app: ssm
    spec:
      containers:
      - image: amazonlinux
        imagePullPolicy: Always
        name: ssm
        command: ["/bin/bash"]
        args: ["-c","yum install -y systemd curl tar sudo procps https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm ; /usr/bin/amazon-ssm-agent"]
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 120
