---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: eks-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://aws.github.io/eks-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: "1.1.6"
      sourceRef:
        kind: HelmRepository
        name: eks-charts
        namespace: flux-system
      interval: 1m
  values:
    serviceAccount:
      create: false
      name: aws-load-balancer-controller
  valuesFrom:
    - kind: ConfigMap
      name: terraform-alb-info
      valuesKey: cluster_name
      targetPath: clusterName
